### ISSUE TITLE
Build Related Discussion

### ISSUE THREAD

**Issue by crederaken** [Waffle/waffle#348]
So I'm on a new Windows 2012 server and running build all...  No matter what I do, I keep running into this error:

"Missing NUnit, expected in Tools\NUnit.Runners"

Do you know if others are having issues installing Waffle on Windows 2012 server?

**Comment by dblock** [comment]
If you're trying to build waffle please check out https://github.com/dblock/waffle/blob/master/Docs/SettingUpDevelopmentEnvironment.md

**Comment by crederaken** [comment]
Yes, of course I went through that.  There is an error in that at least for a new azure server.  The build just doesn’t work properly.  I got past that though by manually copying files.  Now I am trying to get it running in jetty using the instructions for eclipse which also don’t work as written.  Thanks!

Ken Myers | Credera
832.248.8168 | kmyers@credera.com<applewebdata://EC0A52AD-E3D4-4607-86D8-F645D45CE623/smiller@credera.com>
www.credera.com<http://www.credera.com/>

**Comment by dblock** [comment]
Did you install NUnit? Is this something we broke?

**Comment by crederaken** [comment]
I did install Nunit  and for whatever reason the build all script works for every directory except Nunit.runners so I had to manually copy the tools directory from Nunit.consolerunner to get the build all script to work properly.

Ken Myers | Credera
832.248.8168 | kmyers@credera.com<applewebdata://EC0A52AD-E3D4-4607-86D8-F645D45CE623/smiller@credera.com>
www.credera.com<http://www.credera.com/>

**Comment by dblock** [comment]
I'll reopen this, we want it fixed (not sure how).

**Comment by crederaken** [comment]
If you are curious as to the next error after getting the directory copy it is “The type or namespace name ‘ExpectedException’ could not be found (are you missing a using directive or an assembly reference)"

Ken Myers | Credera
832.248.8168 | kmyers@credera.com<applewebdata://EC0A52AD-E3D4-4607-86D8-F645D45CE623/smiller@credera.com>
www.credera.com<http://www.credera.com/>

**Comment by crederaken** [comment]
Okay the build errors are related to the Nunit issues.

Ken Myers | Credera
832.248.8168 | kmyers@credera.com<applewebdata://EC0A52AD-E3D4-4607-86D8-F645D45CE623/smiller@credera.com>
www.credera.com<http://www.credera.com/>

**Comment by dblock** [comment]
@crederaken You might want to reply on Github so your personal info is not all copypasted from email here...

**Comment by crederaken** [comment]
Okay thanks!  Yeah I am getting closer to a successful build but there are a ton of problems on a Windows 2012 server with the instructions and mostly with the unit tests.

**Comment by dblock** [comment]
Please do document all the hacks you had to do here, and PR fixes.

**Comment by crederaken** [comment]
I'll see what I can do. It's too bad because this would be really useful if the process worked smoother. Do you think this is just an OS related problem?  I also don't have the the full Visual Studio dev environment on the Azure server.

**Comment by dblock** [comment]
I haven't set this up in a while, but there're a bunch of contributors here that don't seem to have issues.

**Comment by hazendaz** [comment]
**bootstrap.cmd** in the root will use nuget to get the dependencies.  It grabs latest and greatest when run.  My build from November on my local machine for .net side had this version -> NUnit.Runners.2.6.4.  I saved that off and ran the bootstrap.  It pulled down a lot more for nunit at version 3.2.1.  Everything pulls ok but then it errors as @crederaken has indicated.  Quick fix was to point to what appears new location for tools.  Basically same that @crederaken did.  I repeated all the same issues.

Now I normally don't build the .net side.  And obviously nunit has greatly changed.  I'll have to do a bit of research to see what has changed since 2.6.4.  If we run this with 2.6.4, it works without issue.  Hopefully it's just something trivial.  But first place to really look is at how nunit has changed.  Feel free to submit a PR if you figure it out.  I'm going to start looking now but not sure if I will get this addressed tonight or not.

**Comment by hazendaz** [comment]
@crederaken Build is fixed.  Please rebase with master and give it another shot.  I reverted us back to 2.6.4 for time being so you can proceed.  I'll look to upgrading this to nunit 3.2.1 when I have some more time so we stay current ;)

**Comment by crederaken** [comment]
Yes, that is much better!  There are a few issues still with the WindowsAuthProviderLocalUnitTests.cs tests failing out of the box and after those are cleared there are issues with the pom causing build failures.  Namely: Failed to execute goal pl.project12.maven:git-commit-id-plugin:2.2.1:revision(git-commit-id) on project waffle-jna: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml.

It's much closer though!

**Comment by crederaken** [comment]
Okay, so short of the WindowsAuthProviderLocalUnitTests.cs failing everything else is resolved and I have a successful build.  Any idea what needs to be modified for those tests to pass?  I'll keep working on them but in the meantime everything else works.

For anyone experiencing the same issues.  I would highly recommend just doing a git clone from powershell to resolve any of the above noted git issues.  If you do that then the build executes flawlessly with the exception of the above noted unit tests which you will need to comment out until a fix can be found/explained.

**Comment by hazendaz** [comment]
Git clone is sort of expected.  However maybe i can profile that pluglin to break the dependency.


As for unit test failure.  What is the error you get from that?  Im not seeing any errors and probably due to me using windows 10.


Sent from Outlook Mobile






On Thu, Apr 28, 2016 at 5:24 AM -0700, "Ken Myers" <notifications@github.com> wrote:





Okay, so short of the WindowsAuthProviderLocalUnitTests.cs failing everything else is resolved and I have a successful build.  Any idea what needs to be modified for those tests to pass?  I'll keep working on them but in the meantime everything else works.

For anyone experiencing the same issues.  I would highly recommend just doing a git clone from powershell to resolve any of the above noted git issues.  If you do that then the build executes flawlessly with the exception of the above noted unit tests which you will need to comment out until a fix can be found/explained.

---

**Comment by crederaken** [comment]
Here is a screenshot 
<img width="840" alt="screen shot 2016-04-28 at 8 04 53 am" src="https://cloud.githubusercontent.com/assets/16676195/14886755/18b9b0fc-0d18-11e6-8c77-d3e1dd8e6f85.png">

**Comment by crederaken** [comment]
It would be good as well to show a screenshot of the build settings users should have in eclipse for the application to successfully start (if one is available).  That would be good to add here: https://github.com/dblock/waffle/blob/master/Docs/SettingUpDevelopmentEnvironment.md - Since just selecting run as java application is not adequate in all environments.

**Comment by hazendaz** [comment]
Importing as maven project will auto setup all needed in eclipse.


Sent from Outlook Mobile






On Thu, Apr 28, 2016 at 6:15 AM -0700, "Ken Myers" <notifications@github.com> wrote:





It would be good as well to show a screenshot of the build settings users should have in eclipse for the application to successfully start (if one is available).  That would be good to add here: https://github.com/dblock/waffle/blob/master/Docs/SettingUpDevelopmentEnvironment.md - Since just selecting run as java application is not adequate in all environments.

---

**Comment by crederaken** [comment]
Yes I assumed that would work as well but it did not at least on Windows Server 2012.  I imported it exactly as documented here https://github.com/dblock/waffle/blob/master/Docs/SettingUpDevelopmentEnvironment.md however the build settings are not correct.

**Comment by crederaken** [comment]
Being more specific the problem is: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet - It's probably important to note that I am attempting to run it using jetty as the setup document recommends...

**Comment by crederaken** [comment]
So two problems remain 1) unit testing errors forcing you to skip those unit tests and 2) not quite having the build environment right for jetty.

**Comment by hazendaz** [comment]
Thanks.  Ill take a closer look tonight.


Sent from Outlook Mobile






On Thu, Apr 28, 2016 at 6:34 AM -0700, "Ken Myers" <notifications@github.com> wrote:





So two problems remain 1) unit testing errors forcing you to skip those unit tests and 2) not quite having the build environment right for jetty.

---

**Comment by crederaken** [comment]
Here's a more thorough result from the run:

[main] INFO org.eclipse.jetty.util.log - Logging initialized @332ms
[main] INFO waffle.jetty.StartEmbeddedJetty - >>> STARTING EMBEDDED JETTY SERVER, PRESS ANY KEY TO STOP
[main] INFO org.eclipse.jetty.server.Server - jetty-9.3.z-SNAPSHOT
[main] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@6be46e8f{/,file:///C:/ad/waffle/Source/JNA/waffle-demo/waffle-filter/,AVAILABLE}{../waffle-demo/waffle-filter}
[main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@3bbf1dfb{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
[main] INFO org.eclipse.jetty.server.Server - Started @1330ms

**Comment by crederaken** [comment]
I'll be happy to test all of the above for you when you are ready.  For now I have it up and running under tomcat on a new azure/AD windows 2012 server.  Nothing special required just 'build all' and then drop the war file into tomcat.

**Comment by hazendaz** [comment]
@crederaken I have reopened this issue and renamed it so we can continue discussing the various issues.

Tonight I pushed a patch I wrote last night to raise nunit support to 3.2.1.
I then pushed a fix for the jetty jsp support.
I also added a patch that should allow build with no .git directory.

If you could test all the issues you have discovered so far and let me know if this clears any of them for you.  Then we can continue through other issues you are still seeing.

**Comment by crederaken** [comment]
Okay here are the results:

We still have the same issues with the unit tests and then after commenting those out we have a new error that may or may not be helpful.  I'll provide both screens below for your review:

<img width="842" alt="unittest-errors" src="https://cloud.githubusercontent.com/assets/16676195/14916661/887921a2-0de0-11e6-92a6-95476042f9a6.png">

after commenting the above out now we get: 

<img width="834" alt="build-errors" src="https://cloud.githubusercontent.com/assets/16676195/14916668/93dfb72c-0de0-11e6-9a21-3333304a1da8.png">

**Comment by crederaken** [comment]
After restoring from my stash I now get this as well

<img width="827" alt="repo-error" src="https://cloud.githubusercontent.com/assets/16676195/14917095/f7652c44-0de2-11e6-8666-8185f898aa3a.png">

**Comment by hazendaz** [comment]
@crederaken Sorry for the delay...interesting enough the issue you see above I'm experiencing on another project running on appvoyer.  It for whatever reason has issues getting the license maven plugin.  Have you been able to get past that issue?

**Comment by hazendaz** [comment]
I haven't seen this issue occur in long time.  Other issues all addressed.  I'm running on a brand new machine and it built right out of the box without issues with all tests working.  Closing this issue.  If issues persist please open a new ticket detailing any remaining issue on separate tickets.
